# Generated by Django 4.1.3 on 2023-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_correct_choice_choice_cor_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='cor_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='cor_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
