# Generated by Django 4.1.3 on 2023-03-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_choice_cor_answer_remove_question_cor_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choie_text',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='questoin',
            new_name='question',
        ),
    ]
