# Generated by Django 4.1.3 on 2023-03-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_choie_text_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_type',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
