# Generated by Django 4.1.3 on 2023-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_q_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(max_length=100)),
                ('high_score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('answered_questions', models.IntegerField(default=0)),
            ],
        ),
    ]
