# Generated by Django 4.1.3 on 2023-03-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_User',
        ),
    ]
