# Generated by Django 4.1.3 on 2023-05-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_achievement_remove_customuser_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mythologyquizscore',
        ),
        migrations.AddField(
            model_name='customuser',
            name='answered_questions',
            field=models.IntegerField(default=0),
        ),
    ]
