# Generated by Django 4.1.3 on 2023-05-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_mythologyquizscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='answered_questions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.ManyToManyField(to='accounts.achievement'),
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
