# Generated by Django 4.1.3 on 2023-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_answered_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quizes_done',
            field=models.IntegerField(default=0),
        ),
    ]
