# Generated by Django 4.1.3 on 2023-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_quizes_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
