# Generated by Django 4.1.3 on 2023-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_types',
            name='id',
        ),
        migrations.AlterField(
            model_name='question_types',
            name='q_type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
