# Generated by Django 4.1.3 on 2023-05-19 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_question_types_id_alter_question_types_q_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionforadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('q_type', models.CharField(max_length=200)),
                ('correct_choice', models.CharField(max_length=200)),
                ('incorrect_choice1', models.CharField(max_length=200)),
                ('incorrect_choice2', models.CharField(max_length=200)),
                ('incorrect_choice3', models.CharField(max_length=200)),
                ('who_sent', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
